export enum UserType {
  ADMIN = 'ADMIN', 
  FUNCIONARIO = 'FUNCIONARIO', 
  SERVIDOR_TECNICO_ADMINISTRATIVO = 'SERVIDOR_TECNICO_ADMINISTRATIVO',
  DOCENTE = 'DOCENTE',
  FUNCIONARIO = 'FUNCIONARIO',
}